namespace KnowBe4.Types;

public record User(
    int Id,
    string EmployeeNumber,
    string FirstName,
    string LastName,
    string JobTitle,
    string Email,
    double PhishPronePercentage,
    string PhoneNumber,
    string Extension,
    string MobilePhoneNumber,
    string Location,
    string Division,
    string ManagerName,
    string ManagerEmail,
    bool ProvisioningManaged,
    string ProvisioningGuid,
    List<int> Groups,
    double CurrentRiskScore,
    List<string> Aliases,
    DateTime JoinedOn,
    DateTime LastSignIn,
    string Status,
    string Organization,
    string Department,
    string Language,
    string Comment,
    DateTime EmployeeStartDate,
    DateTime ArchivedAt,
    string CustomField1,
    string CustomField2,
    string CustomField3,
    string CustomField4,
    string CustomDate1,
    string CustomDate2
);